const express = require("express");
const app = express();
const cors = require("cors");
const cookieParser = require("cookie-parser");
const { unknownEndpoint, logger, errorHandler } = require("./utils/middleware");
app.use(cookieParser())
app.use(express.json());
const tasksRouter = require("./controllers/tasks");
const usersRouter = require("./controllers/users");
const googleRouter = require("./controllers/google");
const authRouter = require("./controllers/auth");
app.use(cors());
app.use(logger);
app.use("/api/tasks/", tasksRouter);
app.use("/api/users/", usersRouter);
app.use("/api/auth/", authRouter);
app.use("/api/auth/google/", googleRouter);
app.use(unknownEndpoint);
app.use(errorHandler);
module.exports = app;
