export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILURE = "GET_USER_FAILURE";

export const UPDATE_USER_REQUEST = "UPDATE_USER_REQUEST"
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS"
export const UPDATE_USER_FAILURE = "UPDATE_USER_FAILURE"

export const RESET_USER = "RESET_USER"

export const UPDATE_USER_PASSWORD_REQUEST = "UPDATE_USER_PASSWORD_REQUEST"
export const UPDATE_USER_PASSWORD_FAILURE = "UPDATE_USER_PASSWORD_FAILURE"
export const UPDATE_USER_PASSWORD_SUCCESS = "UPDATE_USER_PASSWORD_SUCCESS"


export const REMOVE_USER_REQUEST = "REMOVE_USER_REQUEST"
export const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS"
export const REMOVE_USER_FAILURE = "REMOVE_USER_FAILURE"

export const UPDATE_PROFILE_PICTURE_REQUEST = "UPDATE_PROFILE_PICTURE_REQUEST"
export const UPDATE_PROFILE_PICTURE_SUCCESS = "UPDATE_PROFILE_PICTURE_SUCCESS"
export const UPDATE_PROFILE_PICTURE_FAILURE = "UPDATE_PROFILE_PICTURE_FAILURE"

export const REMOVE_PROFILE_PICTURE_REQUEST = "REMOVE_PROFILE_PICTURE_REQUEST"
export const REMOVE_PROFILE_PICTURE_SUCCESS = "REMOVE_PROFILE_PICTURE_SUCCESS"
export const REMOVE_PROFILE_PICTURE_FAILURE = "REMOVE_PROFILE_PICTURE_FAILURE"


export const DELETE_PROFILE_PIC_SUCCESS = "DELETE_PROFILE_PIC_SUCCESS"
export const DELETE_PROFILE_PIC_FAILURE = "DELETE_PROFILE_PIC_FAILURE"
export const DELETE_PROFILE_PIC_REQUEST = "DELETE_PROFILE_PIC_REQUEST"

export const CLEAR_MESSAGES = "CLEAR_MESSAGES"
export const SHOW_USER_ACC_DELETION_CONFIRMATION = "SHOW_USER_ACC_DELETION_CONFIRMATION"
export const HIDE_USER_ACC_DELETION_CONFIRMATION = "HIDE_USER_ACC_DELETION_CONFIRMATION"
export const RESET_PASSWORD_UPDATE = "RESET_PASSWORD_UPDATE"